### ISSUE TITLE
runtime: VirtualAlloc of 118390784 bytes failed with errno=1455

### ISSUE THREAD

**Issue by james-sounds-crazy** [lambertjamesd/sfz2n64#1]
Hi, i was unable to convert my sfz to ins. 

Total Memory: 8GB
Memory Used: 2.0GB  -> before execution

sfz size: 28kb
sfz wav sample : 112mb

Command issued :
sfz2n64-and64.exe 000_Grand_Piano.sfz -o grand-piano-YDP_20210103.ins

When command issued, memory consumption ramped up to 7.9GB.
Then execution terminated with the error logs below: 

See attached error logs
[out_of_memory_error_log.txt](https://github.com/lambertjamesd/sfz2n64/files/7800774/out_of_memory_error_log.txt)

Please advise.

Thank you for looking into this....

**Comment by lambertjamesd** [comment]
It is trying allocate the 112mb needed to hold the wav file but fails. While 112mb is pretty bit it is way less than 6GB. So either that memory is being allocated multiple times or something else is going on.

I'm guessing what is going is is your sfz has all the sound samples in the same file and it is referenced multiple times. Each reference loads the sound sample independently and that quickly balloons the memory usage. I probably need to have the program keep track of which sound files have already been loaded and just reuse them.

**Comment by james-sounds-crazy** [comment]
Yes that seems to be a good plan, to reuse...
I try to share as much info about my setup so debugging will be much easier...
Thank you for taking time to look into this... i appreciate it...

**Comment by lambertjamesd** [comment]
I pushed out a fix. See if it works. I uploaded a new release (v1.0) with the fix
